
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_DISCARD_TOKEN = "AUTH_DISCARD_TOKEN";
export const AUTH_SET_USER = "AUTH_SET_USER";
export const AUTH_SET_USER_TEAM = "AUTH_SET_USER_TEAM";
export const SET_CURRENT_APPLICATION = "SET_CURRENT_APPLICATION";
export const REFRESH_AUTH = "REFRESH_AUTH";


